### ISSUE TITLE
Subtitle isn't inserted in PDF version

### ISSUE THREAD

**Issue by ivanhercaz** [pandoc-scholar/pandoc-scholar#28]
Hi!
First of all I want to thank to @tarleb and @robert-winkler for this awesome and useful tool. Now I am writting a paper and I think `pandoc-scholar` is suitable for my necessities and using it I save many time developing my own script. However I am having problems with the subtitle field.

I have the next YAML block:

```yaml
---
title: Spanish title
subtitle: English title
author:
  - Iván Hernández-Cazorla:
      institute: abbrv
      email: name@website.com
      orcid: 0000-0000-0000-0000
institute:
  - abbrv: institution
resumen: 
abstract: |
  Abstract in Spanish
  \begin{center}
  \textbf{Keywords in Spanish}
  \end{center}
  \begin{center}
  \textbf{Abstract}
  \end{center}
  Abstract in English
  \begin{center}
  \textbf{Keywords in English}
  \end{center}
bibliography: bibliography.bib
csl: apa.csl
header-includes: |
  \usepackage[spanish]{babel}
...
```

The main problem is that the subtitle isn't being written in the PDF, but in the HTML it is fine. I don't know the reason. I tried to read the latex template used by pandoc-scholar but I dind't find nothing useful. One thing I tried was to replace the subtitle parts of the template by a subtitle mechanism I have in one script with a default.yaml block (using it without the `header-includes: |` of course):

```yaml
---
header-includes: |
  \providecommand{\subtitle}[1]{%
  \usepackage{titling}
  \posttitle{%
    \par\large#1\end{center}}
  }
  \usepackage[spanish]{babel}
---
```

Anyone knows why it could be happening in this case? Could it be a bug of pandoc-scholar or is it totally related with my document? Ah, and note that I wrote the keywords in Spanish and English inside the abstract, it is due the `keywords` field doesn't work.

Regards
