### ISSUE TITLE
Multiple auhors use "and" when Spanish is the language of the document

### ISSUE THREAD

**Issue by ivanhercaz** [pandoc-scholar/pandoc-scholar#32]
Hi again!

I centered again my eyes in the first page of my paper I have noticed that having more than one author, Pandoc Scholar (or Pandoc, I don't know exactly where is the bug) writes "and" instead of "y". The language of the document is well configured with `lang: es` and the authors are in this format:

```yaml
author:
  - Iván Hernández-Cazorla:
      institute: wmes
      email: name@website.com
      orcid: 0000-0002-5436-8535
  - Manuel Ramírez-Sánchez:
      institute: iatext
      email: name@website.com
      orcid: 0000-0002-4935-7313
  - Gregorio Rodríguez-Herrera:
      institute: iatext
      email: name@website.com
      orcid: 0000-0002-9856-8897
```

![and](https://user-images.githubusercontent.com/8690921/52319492-d924b800-29c1-11e9-9bf8-eaaef69f78a4.png)

Any idea about it? Thanks in advance!

Regards,
Iván
